### ISSUE TITLE
3. Failed: invalid time period: {$DEFAULT_LLD_THROTTLING_HB_PERIOD}

### ISSUE THREAD

**Issue by pompfe** [mykolq/zabbix_lsi_template#13] opened 2024-07-20 18:32 UTC
Avago/LSI 9260 w/ BBU
Zabbix 7.0.0 Server Linux (Ubuntu)
Zabbix 7.0.0 Agent2 active Linux (Ubuntu)

For this:
Template LSI_PERC_Lenovo json discovery: All Ctls and LDs Info: Controllers discovery
I get the result/error:
Preprocessing failed for: {."Controllers":[.{.."Command Status" : {..."Controller" : 0,..."Status" : "Success",..."Descript...
1. Result: {."Controllers":[.{.."Command Status" : {..."Controller" : 0,..."Status" : "Success",..."Descript...
2. Result: [{"Controller number":0,"Has battery":"Yes","Model":"LSI MegaRAID SAS 9260-16i","Serial Number":"...
3. Failed: invalid time period: {$DEFAULT_LLD_THROTTLING_HB_PERIOD}

For this:
Template LSI_PERC_Lenovo json discovery: All Ctls and LDs Info: Logical disks discovery
I get the result/error:
Preprocessing failed for: {."Controllers":[.{.."Command Status" : {..."Controller" : 0,..."Status" : "Success",..."Descript...
1. Failed: invalid time period: {$DEFAULT_LLD_THROTTLING_HB_PERIOD}

Template LSI_PERC_Lenovo json discovery: All Pds LLD info: Physical disks discovery   seems to run, means shows "enabled".

Any Idea what's going wrong?

For {$ADAP_THROTTLING_HB_PERIOD} and the two other where no values are given (README), I used 10800.  Is that correct?

Thanks a lot!

**Comment by pompfe** [comment] 2024-07-20 18:45
I just set {$DEFAULT_LLD_THROTTLING_HB_PERIOD} to 10800 and it works (in parts).  I still don't know what values make sense.

Now I get:
Preprocessing failed for: {."Controllers":[.{.."Command Status" : {..."Controller" : 0,..."Status" : "Success",..."Descript...
1. Result: ST4000NE001-2MA101
2. Failed: invalid time period: {$DEFAULT_ITEM_THROTTLING_PERIOD}

Preprocessing failed for: {."Controllers":[.{.."Command Status" : {..."Controller" : 0,..."Status" : "Success",..."Descript...
1. Result: 0
2. Failed: invalid time period: {$DEFAULT_ITEM_THROTTLING_PERIOD}

Invalid update interval "{$ADAP_BATTERY_REQUEST_PERIOD}".

Many of them!

**Comment by pompfe** [comment] 2024-07-20 18:55
And now I set these two above to 10800, too.  Now it works.

Are these values really meant to be set by me?  Am I the only one, as nobody else complained?  Strange...
Is there something somewhere that I did not read?

Now I have set everything missing to 10800.  But I have no clue what the values should be really set to.  Or even if I really have to set them myself.  Maybe something is different/missing in 7.0.0 ...

Btw, "All Ctls and LDs Info", "All Pds info", "Controller 0 all battery (BBU) info" are empty (no value returned). They are internal, right?

Any help would be great!  Thank you!

**Comment by MIPMHannes** [comment] 2024-08-06 16:04
> Btw, "All Ctls and LDs Info", "All Pds info", "Controller 0 all battery (BBU) info" are empty (no value returned). They are internal, right?

Yes this is expected behaviour. These items are just there for gethering data. There a child items which proccess and store the data.


> Are these values really meant to be set by me? Am I the only one, as nobody else complained? Strange...
> Is there something somewhere that I did not read?

Yes you can set them. You are not the only one complaining. In fact there is already a fix -> #3 But @mykolq  did not merged it just yet.  

> Now I have set everything missing to 10800. But I have no clue what the values should be really set to. Or even if I really have to set them myself. Maybe something is different/missing in 7.0.0 ...

This has nothing todo with zabbix version 7. The default values are just missing.

**Comment by pompfe** [comment] 2024-08-14 09:38
Thanks for your comment.

Btw, {$DEFAULT_HISTORY_PERIOD} seems to be missing. Houskeeper shows lots of "invalid history storage period '{$DEFAULT_HISTORY_PERIOD}' for itemid 'xxxxx'".

**Comment by MIPMHannes** [comment] 2024-08-14 11:12
Just set {$DEFAULT_HISTORY_PERIOD} Macro. I set it to 30d. I see its missing in #3 too.
I will try to make a new PR in the next days to add the default macros. Maybe @mykolq did not accept the PR because it was incomplete.

**Comment by pompfe** [comment] 2024-08-14 11:19
Yes, that's what I did. Just wanted to mention... Did not look into the logs for a longer time.

**Comment by MIPMHannes** [comment] 2024-08-14 11:28
Yes I figured that. I made a new PR #15 to add defaults

**Comment by MIPMHannes** [comment] 2024-08-16 06:59
PR was merged. I belive we can close this now?

**Closed as completed** 2024-08-16 09:03 UTC
